name: dbt_WS_snowflake
version: '1.0'
config-version: 2

profile: default

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt_snowflake:
    +materialized: table
    example:
      +materialized: table
